
# CI de Nivel 04 - Disparo dos testes dentro do pipe de dev

# nome do nosso 'pipeline'

name: 'Execução Integrada'

# regras de disparo (gatilhos/triggers)
# gatilho de execução manual = workflow_dispatch
# gatilho de execução agendada = schedule
# gatilho de execução a partir de outro pipe = workflow_run
on:
  workflow_dispatch:
   

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  inspecao:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Checando padronizacao do codigo
        run: yarn lint


  unidade:
    run-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Executando testes de unidade
        run: yarn tests


  e2e-tests:
     run-on: ubuntu-latest

     steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install 

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled()}}
        with:
          name: relatorio
          path: ./playwright-report



  deploy:
    # máquina que o job vai executar
    runs-on: ubuntu-latest

    steps:
    - name: Simulação do deploy
      run: echo "Simulando o deploy com sucesso" 

   