
# CI de Nivel 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'

name: 'Testes de Execucação Manual' 

# regras de disparo (gatilhos/triggers)
# gatilho de execução manual = workflow_dispatch
on:
  workflow_dispatch:


# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-testes:
    # máquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e "trabalho-final.js"
      

